// data.ts
import { Tool, CarouselItem } from "./types";
import { 
  ImageIcon, VideoIcon, ZapIcon, PenToolIcon, SearchIcon, 
  FilmIcon, RotateCwIcon, WavesIcon 
} from "lucide-react";

// Tools data
export const tools: Tool[] = [
  {
    id: "1",
    name: "Image",
    description: "Create AI art using prompts with creativity",
    category: "Generate",
    isNew: true,
    icon: <ImageIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-blue-700 to-blue-400",
  },
  {
    id: "2",
    name: "Yellow",
    description: "Sequence prompts with midjourney style video generator",
    category: "Generate",
    icon: <FilmIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-yellow-700 to-yellow-400",
  },
  {
    id: "3",
    name: "RealTime",
    description: "Generate images using prompts in real-time",
    category: "Generate",
    icon: <ZapIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-green-700 to-green-400",
  },
  {
    id: "4",
    name: "Enhancer",
    description: "Upscale and enhance images using AI",
    category: "Generate",
    isNew: true,
    icon: <SearchIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-purple-700 to-purple-400",
  },
  {
    id: "5",
    name: "Loft",
    description: "Generate images with sketches",
    category: "Generate",
    isPro: true,
    icon: <PenToolIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-orange-700 to-orange-400",
  },
  {
    id: "6",
    name: "Video Upscaler",
    description: "Enhance your images for FLUX.1 training",
    category: "Generate",
    isPro: true,
    icon: <VideoIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-red-700 to-red-400",
  },
  {
    id: "7",
    name: "Motion Transfer",
    description: "Create video animations",
    category: "Generate",
    isPro: true,
    icon: <RotateCwIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-indigo-700 to-indigo-400",
  },
  {
    id: "8",
    name: "Flux",
    description: "Generate videos or replicate your style",
    category: "Generate",
    icon: <WavesIcon className="h-6 w-6 text-white" />,
    color: "bg-gradient-to-br from-teal-700 to-teal-400",
  },
];

// Carousel items data
export const carouselItems: CarouselItem[] = [
  {
    id: "1",
    title: "WAN 2.2",
    subtitle: "WAN 2.2 Image generation",
    description: "Generate complex images with the brand new WAN 2.2 model. Exceptional prompt adherence and realistic textures.",
    image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try WAN 2.2",
    type: "AI Model",
  },
  {
    id: "2",
    title: "Open Source",
    subtitle: "FLUX1 Krea",
    description: "We make AI art designed to put FLUX.1 into movie-maker. Quick editing, better prompts, open the technical report of FLUX.",
    image: "https://images.pexels.com/photos/618612/pexels-photo-618612.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try FLUX1",
    type: "AI Model",
  },
  {
    id: "3",
    title: "Stable Diffusion XL",
    subtitle: "Advanced diffusion model",
    description: "High-quality image generation with flexible prompt handling. Great for both creativity and production use cases.",
    image: "https://images.pexels.com/photos/3182749/pexels-photo-3182749.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try SDXL",
    type: "AI Model",
  },
  {
    id: "4",
    title: "Midjourney V6",
    subtitle: "Creative visuals",
    description: "Generate unique art styles with Midjourney V6. Perfect for design, branding, and concept visuals.",
    image: "https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try Midjourney",
    type: "AI Model",
  },
  {
    id: "5",
    title: "Runway Gen-2",
    subtitle: "AI video generation",
    description: "Text-to-video capabilities with Runway Gen-2. Transform prompts into cinematic sequences.",
    image: "https://images.pexels.com/photos/723240/pexels-photo-723240.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try Runway",
    type: "AI Model",
  },
  {
    id: "6",
    title: "ChatGPT Vision",
    subtitle: "Text + Image input",
    description: "Multi-modal understanding. Upload images and get rich context responses with ChatGPT Vision.",
    image: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try GPT Vision",
    type: "AI Model",
  },
  {
    id: "7",
    title: "Claude 3",
    subtitle: "Anthropic’s flagship",
    description: "Powerful natural language reasoning. Excellent for long-form writing, coding, and analysis.",
    image: "https://images.pexels.com/photos/270637/pexels-photo-270637.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try Claude",
    type: "AI Model",
  },
  {
    id: "8",
    title: "Gemini Ultra",
    subtitle: "Google DeepMind",
    description: "State-of-the-art multi-modal AI from Google. Combines reasoning, creativity, and factual accuracy.",
    image: "https://images.pexels.com/photos/374870/pexels-photo-374870.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try Gemini",
    type: "AI Model",
  },
  {
    id: "9",
    title: "LLaMA 3",
    subtitle: "Open weights model",
    description: "Meta’s open-source LLaMA 3 model for research and production. Flexible, transparent, and community-driven.",
    image: "https://images.pexels.com/photos/356830/pexels-photo-356830.jpeg?auto=compress&cs=tinysrgb&w=600",
    buttonText: "Try LLaMA",
    type: "AI Model",
  },
];
